workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: '$CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH == "main"'
      when: always

stages:
  - build

image: node:latest
build:
  stage: build

  before_script:
    - apt update -qq
    - apt-get update -y
    - apt-get install awscli -y
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set region $AWS_DEFAULT_REGION

  script:
    - npm install
    - npm install typescript
    - npm run build
    - ls -ltr
    - ls -ltr build/bundle/    
    - aws s3 cp build/bundle/bundle.js.gz s3://thanos-koii/test --recursive
    - aws s3 cp build/bundle/bundle.js s3://thanos-koii/test --recursive  
