workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: '$CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH == "main"'
      when: always

stages:
  - build

image: node:latest
build:
  stage: build

  before_script:
    - apt update -qq
    - apt-get update -y
    - apt-get install awscli -y
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set region us-east-1

  script:
    - npm install
    - npm install typescript
    - npm run build
    - ls -ltr
    - ls -ltr build/bundle/  
    - aws s3 ls
    - aws s3 cp ./build/bundle/ s3://cdn.koii.live/build --recursive 
